<section id="profile-timeline-section">
    <?= $this->render('user/profile/index/profile-pic.phtml') ?>
</section> <!-- /#profile-timeline-section -->

<section id="page-content">
    <div class="container">
        <?= $this->render('user/profile/index/instuctor-profile.phtml') ?>
        <?= $this->render('user/profile/index/review-list.phtml') ?>
        <?= $this->render('user/profile/index/course-list.phtml') ?>
        <?= $this->render('user/profile/index/class-list.phtml') ?>
    </div>
</section>